#include <extdll.h>
#include <meta_api.h>
#include <stdio.h>
#include <string.h>
#include "ex_rehlds_api.h"
#include "cvars.h"
#include "entity_state.h"
#include "cbase.h"
#include "weapons.h"
#include "player.h"
#include "enginecallback.h"